// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <algorithm>
#include <string>
#include <vector>

using namespace Rcpp;

// numeric_to_factor
CharacterVector numeric_to_factor(NumericVector num, CharacterVector levs, bool na_to_missing = true);
RcppExport SEXP mungebitsTransformations_numeric_to_factor(SEXP numSEXP, SEXP levsSEXP, SEXP na_to_missingSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        NumericVector num = Rcpp::as<NumericVector >(numSEXP);
        CharacterVector levs = Rcpp::as<CharacterVector >(levsSEXP);
        bool na_to_missing = Rcpp::as<bool >(na_to_missingSEXP);
        CharacterVector __result = numeric_to_factor(num, levs, na_to_missing);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}

 /*
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP mungebitsTransformations_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
*/
