// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// numeric_to_factor
CharacterVector numeric_to_factor(NumericVector num, CharacterVector levs, bool na_to_missing = true);
RcppExport SEXP syberiaMungebits_numeric_to_factor(SEXP numSEXP, SEXP levsSEXP, SEXP na_to_missingSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type num(numSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type levs(levsSEXP );
        Rcpp::traits::input_parameter< bool >::type na_to_missing(na_to_missingSEXP );
        CharacterVector __result = numeric_to_factor(num, levs, na_to_missing);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
