# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numeric_to_factor <- function(num, levs, na_to_missing = TRUE) {
    .Call('mungebitsTransformations_numeric_to_factor', PACKAGE = 'mungebitsTransformations', num, levs, na_to_missing)
}

