# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mungebitsTransformations_numeric_to_factorC <- function(num, levs, na_to_missing = TRUE) {
    .Call('mungebitsTransformations_mungebitsTransformations_numeric_to_factorC', PACKAGE = 'mungebitsTransformations', num, levs, na_to_missing)
}

